

const resList = [{
  id: 1,
  resImage: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/sgmiii6h0go1zehv6m9j",
  resName: "Meghna foods",
  rating: 3.5,
  time: "30-40 minutes",
  cuisine: "Biryani",
  priceForTwo: "200",
  pureVeg: "NO",
},
{
  id: 2,
  resImage: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcThv3ZTintqJ01INXKWzVIOoVA_xygDgnF4axKB68RyUEtn_s--CZtDB-1c8shBQoyYzxQ&usqp=CAU",
  resName: "Mapango",
  rating: 4.5,
  cuisine: "Italian",
  time: "25 minutes",
  priceForTwo: "400",
  pureVeg: "Yes",
},
{
  id: 3,
  resName: "Romes",
  resImage: "https://cdn.pixabay.com/photo/2021/05/25/02/03/restaurant-6281067_960_720.png",
  rating: 3.2,
  cuisine: "Mexican",
  time: "30 minutes",
  priceForTwo: "350",
  pureVeg: "Yes",
},
{
  id: 4,
  resName: "Food Town",
  resImage: "https://i.pinimg.com/originals/77/7d/9c/777d9c6e187bfc29677c7de89aa73c5a.jpg",
  rating: 3.7,
  cuisine: "Indian",
  time: "25 minutes",
  priceForTwo: "250",
  pureVeg: "NO"
},
{
  id: 5,
  resImage: "https://thumbs.dreamstime.com/b/dinner-icon-trendy-dinner-logo-concept-white-background-dinner-icon-trendy-dinner-logo-concept-white-background-131149368.jpg",
  resName: "Smart Point",
  rating: 4.0,
  cuisine: "IceCream",
  time: "30 minutes",
  priceForTwo: "60",
  pureVeg: "Yes"
},
{
  id: 6,
  resImage: "https://i.pinimg.com/736x/eb/4f/74/eb4f749fd1c95eefe5cccbcd325d8299.jpg",
  resName: "Pandit Juice Corner",
  rating: 4.1,
  cuisine: "Bevrages",
  time: "15 minutes",
  priceForTwo: "100",
  pureVeg: "Yes"
},
{
  id: 7,
  resImage: "https://png.pngtree.com/png-clipart/20190313/ourmid/pngtree-planar-cartoon-street-view-shop-restaurant-and-vendor-elements-png-image_848867.jpg",
  resName: "Royal Restraunt",
  rating: 4.2,
  cuisine: "North Indian",
  time: "25 minutes",
  priceForTwo: "500",
  pureVeg: "NO"
},
{
  id: 8,
  resImage: "https://t4.ftcdn.net/jpg/05/85/29/13/360_F_585291338_0J8Q8vYbKDCu8yqqwAO8PsQZ4ESP2zd8.jpg",
  resName: "Burger Hub",
  rating: 4.1,
  cuisine: "burger",
  time: "25 minutes",
  priceForTwo: "200",
  pureVeg: "NO"
},
{
  id: 9,
  resImage: "https://img.freepik.com/premium-vector/restaurant-building-icon-vector-illustration-with-outline_193397-31.jpg",
  resName: "Pal Dhabba",
  rating: 3.8,
  cuisine: "north-indian",
  time: "25 minutes",
  priceForTwo: "300",
  pureVeg: "Yes"
},
{
  id: 10,
  resImage: "https://t3.ftcdn.net/jpg/06/11/01/26/360_F_611012694_YztSwcyDjHflPhlil3LfeSDXMtew2Scy.jpg",
  resName: "Fozi Dhabba",
  rating: 3.8,
  cuisine: "north-indian",
  time: "25 minutes",
  priceForTwo: "400",
  pureVeg: "NO"
},
{
  id: 11,
  resImage: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRVK6QJOx0qYib3qZMVe8sq1Kl-bLD2GLi6T6USVpJN3Q&s",
  resName: "Gopali",
  rating: 4.2,
  cuisine: "chinese",
  time: "20 minutes",
  priceForTwo: "80",
  pureVeg: "Yes",
},
{
  id: 12,
  resImage: "https://t3.ftcdn.net/jpg/05/68/12/34/360_F_568123469_wPEOJpuXdqbdxmwIHmcH2U6iqYdRIdmn.jpg",
  resName: "Baba ka Dhaba",
  rating: 4.2,
  cuisine: "Desert",
  time: "10 minutes",
  priceForTwo: "20",
  pureVeg: "Yes",
},
{
  id: 13,
  resImage: "https://i.pinimg.com/474x/b1/17/71/b11771d251efe326b40279d40f41157d.jpg",
  resName: "KFC",
  rating: 4.2,
  cuisine: "chicken",
  time: "20 minutes",
  priceForTwo: "400",
  pureVeg: "NO",
},
{
  id: 14,
  resImage: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQU3cKOLdmn8IWbPfdEPNOr_jHNq1upwm4RQ-MHCTPu9w&s",
  resName: "Roll Express",
  rating: 4.2,
  cuisine: "kathi Rolls",
  time: "15 minutes",
  priceForTwo: "100",
  pureVeg: "Yes",
},
{
  id: 15,
  resImage: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRIqcvJmMrXzJgqPCYKRWMYxH_PeI0yemNRspJ_S6EDLw&s",
  resName: "Biryani Blues",
  rating: 4.2,
  cuisine: "South Indain",
  time: "30 minutes",
  priceForTwo: "280",
  pureVeg: "NO",
}

];

export default resList;